modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/lemonszz/taniwha/issues"
license = "MIT"

[[mods]]
modId = "taniwha"
version = "${version}"
displayName = "Taniwha"
authors = "Lemons"
description = '''
Library for LASER KNIGHTS mods (Biome Makeover)
'''
#logoFile = ""

[[dependencies.taniwha]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.taniwha]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.taniwha]]
modId = "architectury"
mandatory = true
versionRange = "[6.0.34,)"
ordering = "AFTER"
side = "BOTH"