name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        id: build
        run: ./gradlew setupActions build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create a Release"
        id: create_release
        uses: meeDamian/github-release@2.0
        with:
          tag: ${{ steps.build.outputs.version }}
          files: "fabric/build/libs/${{ steps.build.outputs.modid }}-fabric-${{ steps.build.outputs.version }}.jar forge/build/libs/${{ steps.build.outputs.modid }}-forge-${{ steps.build.outputs.version }}.jar"
          gzip: false
          name: "${{ steps.build.outputs.modid }}-${{ steps.build.outputs.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"

